# -*- coding: utf-8 -*-
"""Soal-1_SistemPakar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16hjPzajilgc-lwp5miQgo-Oo9RdHJDEJ
"""

def deteksi_hama(gejala):
    if "daun menguning" in gejala:
        return "Hama: Kutu Daun"
    elif "bercak hitam" in gejala:
        return "Penyakit: Jamur"
    elif "daun berlubang" in gejala:
        return "Hama: Ulat"
    elif "tanaman layu" in gejala:
        return "Hama: Nematoda"
    else:
        return "Gejala tidak ditemukan"

gejala_list = [
    "daun menguning",
    "bercak hitam",
    "daun berlubang",
    "tanaman layu"
]

print("=== Sistem Pakar: Identifikasi Hama pada Tanaman ===\n")
print("Pilihan Gejala yang Dapat Dipilih:")
for nomor, gejala in enumerate(gejala_list, start=1):
    print(f"{nomor}. {gejala}")

user_input = input("\nTuliskan gejala yang dialami tanaman (pisahkan dengan tanda koma):\n> ")

gejala_terpilih = [item.strip().lower() for item in user_input.split(",")]

print("\n=== Hasil Analisis ===")
for gejala in gejala_terpilih:
    hasil = deteksi_hama(gejala)
    print(f"- {gejala.title()} : {hasil}")